name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Build
        run: ./gradlew build
      - name: Upload artifact
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*goldbounce-b[0-9|.]*\.jar')
          export LB_VERSION=$(echo $JAR | sed -r 's/.\/goldbounce-([a-zA-Z][0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION
          cp $JAR zip/goldbounce.jar
          cd zip
          zip -r goldbounce.zip *
